image: node:20
stages:
  - test

test_js:
  stage: test
  script:
    - cd js
    - npm install
    - npm test
  artifacts:
    paths:
      - js/node_modules/
      - js/coverage/
    reports:
        junit: js/report.xml

test_ts:
  stage: test
  script:
    - cd ts
    - npm install
    - npm test
  artifacts:
    paths:
      - ts/node_modules/